# Generated by Django 4.1.3 on 2022-11-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
