# Generated by Django 4.1.3 on 2022-12-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='price',
        ),
    ]
